# Generated by Django 6.0.6 on 2026-06-26 09:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memories', '0002_gallerysettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memory',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
